#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define MESSAGE_HEADER_SIZE 4

typedef enum tmessage_type_e {
    kMESSAGE_TYPE_HELLO = 0x01,
    kMESSAGE_TYPE_REGISTER = 0x02,
    kMESSAGE_TYPE_REGISTER_ACK = 0x03,
    kMESSAGE_TYPE_LIST = 0x04,
    kMESSAGE_TYPE_LIST_REPLY = 0x05,
    kMESSAGE_TYPE_OPEN = 0x06,
    kMESSAGE_TYPE_CLOSE = 0x07,
    kMESSAGE_TYPE_SUBSCRIBE = 0x08,
    kMESSAGE_TYPE_ERROR = 0x09,
    kMESSAGE_TYPE_OPEN_ACK = 0x0A,
    kMESSAGE_TYPE_ADMIN_STATUS = 0x10,
    kMESSAGE_TYPE_ADMIN_STATUS_REPLY = 0x11,
    kMESSAGE_TYPE_ADMIN_PEERS = 0x12,
    kMESSAGE_TYPE_ADMIN_PEERS_REPLY = 0x13,
    kMESSAGE_TYPE_ADMIN_KICK = 0x14,
    kMESSAGE_TYPE_ADMIN_KICK_REPLY = 0x15,
    kMESSAGE_TYPE_ADMIN_PINS = 0x16,
    kMESSAGE_TYPE_ADMIN_PINS_REPLY = 0x17,
    kMESSAGE_TYPE_ADMIN_FORGET = 0x18,
    kMESSAGE_TYPE_ADMIN_FORGET_REPLY = 0x19,
    kMESSAGE_TYPE_ADMIN_KICK_PEER = 0x1A,
    kMESSAGE_TYPE_ADMIN_KICK_PEER_REPLY = 0x1B,
    kMESSAGE_TYPE_ADMIN_AGENTS = 0x1C,
    kMESSAGE_TYPE_ADMIN_AGENTS_REPLY = 0x1D,
    kMESSAGE_TYPE_ADMIN_CLIENTS = 0x1E,
    kMESSAGE_TYPE_ADMIN_CLIENTS_REPLY = 0x1F,
    kMESSAGE_TYPE_ADMIN_INTERFACES = 0x20,
    kMESSAGE_TYPE_ADMIN_INTERFACES_REPLY = 0x21,
    kMESSAGE_TYPE_ADMIN_PIN_ADD = 0x22,
    kMESSAGE_TYPE_ADMIN_PIN_ADD_REPLY = 0x23,
    kMESSAGE_TYPE_ADMIN_ACL_SET = 0x24,
    kMESSAGE_TYPE_ADMIN_ACL_SET_REPLY = 0x25,
    kMESSAGE_TYPE_ADMIN_ACL_REVOKE = 0x26,
    kMESSAGE_TYPE_ADMIN_ACL_REVOKE_REPLY = 0x27,
    kMESSAGE_TYPE_ADMIN_ACL_LIST = 0x28,
    kMESSAGE_TYPE_ADMIN_ACL_LIST_REPLY = 0x29,
    kMESSAGE_TYPE_FRAME = 0x40,
    kMESSAGE_TYPE_PING = 0x7F,
    kMESSAGE_TYPE_MAX,
} TMESSAGE_TYPE;

typedef struct {
    uint8_t type;
    uint8_t flags;
    uint16_t length;
} MessageHeader;

size_t MessageHeader_Encode(const MessageHeader *self, uint8_t *buffer, size_t buffer_size);
bool MessageHeader_Decode(MessageHeader *self, const uint8_t *buffer, size_t buffer_size);
